"""
Strategy Models

Investment strategies generated by AI based on user profiles.
"""

from datetime import datetime, UTC
from typing import Optional
from uuid import uuid4

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ...database import Base


def utcnow():
    return datetime.now(UTC)


class Strategy(Base):
    """AI-generated investment strategy."""

    __tablename__ = "strategies"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    user_id: Mapped[str] = mapped_column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    # Strategy identity
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    strategy_type: Mapped[str] = mapped_column(String(50), nullable=False)

    # Risk & time
    risk_level: Mapped[int] = mapped_column(Integer, nullable=False)  # 1-5
    time_horizon: Mapped[str] = mapped_column(String(50), nullable=False)  # short, medium, long

    # Composition - JSON list of assets
    assets: Mapped[dict] = mapped_column(JSON, nullable=False)

    # AI-generated content
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    risks: Mapped[str] = mapped_column(Text, nullable=False)
    learning_points: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)

    # Metadata
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)

    # Relationships
    user = relationship("User", backref="strategies", passive_deletes=True)


class StrategyComparison(Base):
    """AI-generated comparison of multiple strategies."""

    __tablename__ = "strategy_comparisons"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid4()))
    user_id: Mapped[str] = mapped_column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    # List of strategy IDs being compared
    strategy_ids: Mapped[list] = mapped_column(JSON, nullable=False)

    # AI-generated comparison text
    comparison_text: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # Relationships
    user = relationship("User", backref="strategy_comparisons", passive_deletes=True)
